### ISSUE TITLE
Freezing and lag when scrolling on long sites

### ISSUE THREAD

**Issue by nyanpasu64** [ris58h/bar-breaker#6]
## Steps

- Optionally create an empty or refreshed Firefox profile.
- Install Bar Breaker. This extension is necessary and sufficient for lag.
- Visit https://pytorch.org/docs/stable/torch.html (a very long site) and wait for loading to finish.
- Start pressing Page Up or Down.

## Result

Nearly every time you press Page Up or Down, Firefox freezes for a full second before scrolling.

If you wheel-scroll, scrolling appears smooth but the page becomes unresponsive anyway. If you scroll too far, the edges of the page turn white.

If you drag the scrollbar, it's sometimes smooth and sometimes the page turns white.

## System

Windows 10 x64, Firefox 74.0 (64-bit). This occurs on both Direct3D 11 (Advanced Layers) and WebRender.

Unfortunately, Firefox's performance tools aren't great here, and F12 Performance capture doesn't show what code is responsible. So I had to copy my profile when tracing down this issue.

**Comment by ris58h** [comment]
It's because the extension tries to find fixed bars on a page by checking the nodes after each scroll. I will investigate how it can be optimized.

**Comment by ris58h** [comment]
Coming soon in 0.4.4
